# EXODUS_GUI_ui.py for EXODUS v0.1.4
#
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Bernhard Massani
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version. It is distributed WITHOUT ANY WARRANTY; see the LICENSE
# file or <https://www.gnu.org/licenses/> for details.
#
# ----------------------------------------------------------------------------
#
# Layout of the EXODUS main window (class Ui_MainWindow, used by
# EXODUS_main.MainWindow).
#
# Originally generated by the PyQt5 UI code generator 5.15.10 (pyuic5) from
# EXODUS_GUI_placeholders.ui and then EDITED BY HAND: the pyqtgraph plot
# widgets, the Dioptas-style LUT (lut_toolbox), the JCPDS table columns and
# several size policies are set up here and cannot be expressed in Qt
# Designer. Do NOT regenerate this file with pyuic5; transfer layout
# changes made in the .ui file by hand instead.
#
# ============================================================================
#                              Imported libraries
# ============================================================================
from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg
import lut_toolbox
import numpy as np


# =====================================================================
# Digit-wheel spin boxes
# ---------------------------------------------------------------------
# Hovering the mouse over a particular digit of the displayed number and
# scrolling the wheel steps that digit (XDI-style). E.g. with the
# cursor on the tenths digit, one wheel notch changes the value by 0.1;
# on the hundreds digit, by 100. When the cursor is not over any digit
# (over the suffix/prefix, or the spinner is not focused under the
# mouse), behaviour falls back to the spin box's pre-set singleStep.
#
# The classes are aliased onto QtWidgets.QDoubleSpinBox and
# QtWidgets.QSpinBox at module import time so every spinbox created by
# the rest of EXODUS_GUI_ui.py (and by EXODUS_main.py — which imports
# QtWidgets from PyQt5 directly, but resolves QtWidgets.QDoubleSpinBox
# at call time) automatically inherits the new wheel behaviour.
# =====================================================================
_OriginalQDoubleSpinBox = QtWidgets.QDoubleSpinBox
_OriginalQSpinBox       = QtWidgets.QSpinBox


def _digit_step_for_position(spinbox, mouseX):
    """Return the step size that corresponds to the digit under
    ``mouseX`` (in widget coordinates) in ``spinbox``'s displayed text.
    Returns ``None`` if the cursor is not over a digit (e.g. it's on
    the spinner arrows, the suffix, the decimal separator, or outside
    the line-edit's text area).
    """
    line_edit = spinbox.lineEdit()
    if line_edit is None:
        return None

    # Map the mouse x from the spinbox to the embedded line-edit.
    le_x = mouseX - line_edit.x()
    if le_x < 0 or le_x > line_edit.width():
        return None

    text = line_edit.text()
    if not text:
        return None

    # Trim prefix/suffix so we only consider the numeric portion.
    prefix = spinbox.prefix() or ""
    suffix = spinbox.suffix() or ""
    num_start = len(prefix)
    num_end = len(text) - len(suffix)
    if num_start >= num_end:
        return None

    # Find which character index the mouse sits over via the line edit's
    # own cursor mapping. cursorPositionAt() returns the position to
    # the LEFT of the character at that x, so we treat that as "the
    # character to the right of the cursor" — which is the digit the
    # user is visually pointing at.
    cursor_pos = line_edit.cursorPositionAt(QtCore.QPoint(le_x, line_edit.height() // 2))
    if cursor_pos >= len(text):
        cursor_pos = len(text) - 1
    if cursor_pos < num_start or cursor_pos >= num_end:
        return None

    char = text[cursor_pos]
    if not char.isdigit():
        return None

    numeric_text = text[num_start:num_end]
    # Locate decimal point (locale-aware: accept both '.' and ',')
    dot_index = -1
    for sep in ('.', ','):
        idx = numeric_text.find(sep)
        if idx != -1:
            dot_index = idx
            break

    # Local index of the hovered character inside the numeric substring
    local_idx = cursor_pos - num_start

    if dot_index == -1:
        # Integer-only: rightmost digit is units, next is tens, etc.
        # numeric_text may contain a leading sign; skip it for power.
        digits_only = numeric_text.lstrip('+-')
        sign_offset = len(numeric_text) - len(digits_only)
        digit_pos_from_right = (len(numeric_text) - 1) - local_idx
        if local_idx < sign_offset:
            return None
        power = digit_pos_from_right
    else:
        if local_idx < dot_index:
            # Integer side: power = number of digits between this digit
            # and the decimal point (exclusive of the dot).
            power = (dot_index - 1) - local_idx
        elif local_idx == dot_index:
            return None  # cursor on the decimal point itself
        else:
            # Fractional side: power = -(distance after the dot)
            power = -(local_idx - dot_index)

    return 10.0 ** power


class DigitWheelDoubleSpinBox(_OriginalQDoubleSpinBox):
    """QDoubleSpinBox whose wheel step depends on which digit the
    mouse hovers over. See module-level docstring."""

    def wheelEvent(self, event):
        # angleDelta().y() is +120 per notch up (typical mouse wheel).
        delta = event.angleDelta().y()
        if delta == 0:
            event.ignore()
            return
        notches = delta / 120.0

        step = _digit_step_for_position(self, event.x())
        if step is None:
            # Fallback: pre-set singleStep (default behaviour)
            super().wheelEvent(event)
            return

        new_value = self.value() + notches * step
        # Clamp to spinbox limits.
        new_value = max(self.minimum(), min(self.maximum(), new_value))
        self.setValue(new_value)
        event.accept()


class DigitWheelSpinBox(_OriginalQSpinBox):
    """QSpinBox variant of DigitWheelDoubleSpinBox (integer steps).
    For fractional digit positions the step rounds up to 1."""

    def wheelEvent(self, event):
        delta = event.angleDelta().y()
        if delta == 0:
            event.ignore()
            return
        notches = delta // 120 if delta > 0 else -((-delta) // 120)
        if notches == 0:
            notches = 1 if delta > 0 else -1

        step = _digit_step_for_position(self, event.x())
        if step is None:
            super().wheelEvent(event)
            return

        # Integer spin box: round step to nearest integer >= 1.
        int_step = max(1, int(round(step)))
        new_value = self.value() + notches * int_step
        new_value = max(self.minimum(), min(self.maximum(), new_value))
        self.setValue(new_value)
        event.accept()


# Monkey-patch: every QtWidgets.QDoubleSpinBox / QtWidgets.QSpinBox
# created from now on (in this file AND in EXODUS_main.py, since it
# also resolves the name via QtWidgets) is actually a DigitWheel*Box.
# The originals are preserved in module-level globals above in case
# anything needs them.
QtWidgets.QDoubleSpinBox = DigitWheelDoubleSpinBox
QtWidgets.QSpinBox       = DigitWheelSpinBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # Start-up size. EXODUS_main re-applies this, clamped to
        # the available screen, and then sets the panel proportions.
        MainWindow.resize(2440, 1920)
        MainWindow.setStyleSheet("color: white;\n"
"background-color: rgb(61, 61, 61);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_12 = QtWidgets.QFrame(self.centralwidget)
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_11.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_12)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.groupBox_3)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_loadPoni = QtWidgets.QPushButton(self.frame)
        self.pushButton_loadPoni.setObjectName("pushButton_loadPoni")
        self.horizontalLayout.addWidget(self.pushButton_loadPoni)
        self.lineEdit_poniList = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_poniList.setObjectName("lineEdit_poniList")
        self.horizontalLayout.addWidget(self.lineEdit_poniList)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.doubleSpinBox_twoThetaMin = QtWidgets.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_twoThetaMin.setSingleStep(0.5)
        self.doubleSpinBox_twoThetaMin.setProperty("value", 5.0)
        self.doubleSpinBox_twoThetaMin.setObjectName("doubleSpinBox_twoThetaMin")
        self.horizontalLayout.addWidget(self.doubleSpinBox_twoThetaMin)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.doubleSpinBox_twoThetaMax = QtWidgets.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_twoThetaMax.setDecimals(2)
        self.doubleSpinBox_twoThetaMax.setSingleStep(0.5)
        self.doubleSpinBox_twoThetaMax.setProperty("value", 25.0)
        self.doubleSpinBox_twoThetaMax.setObjectName("doubleSpinBox_twoThetaMax")
        self.horizontalLayout.addWidget(self.doubleSpinBox_twoThetaMax)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_4 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_loadFiles = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_loadFiles.setObjectName("pushButton_loadFiles")
        self.horizontalLayout_3.addWidget(self.pushButton_loadFiles)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_recalculateBG = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_recalculateBG.setObjectName("pushButton_recalculateBG")
        self.horizontalLayout_3.addWidget(self.pushButton_recalculateBG)
        # "Remove Pattern" button (name matches the earlier
        # placeholder .ui, pushButton_8_deltePattern)
        self.pushButton_8_deltePattern = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_8_deltePattern.setObjectName("pushButton_8_deltePattern")
        self.horizontalLayout_3.addWidget(self.pushButton_8_deltePattern)
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.spinBox_PatternNumber = QtWidgets.QSpinBox(self.frame_5)
        self.spinBox_PatternNumber.setEnabled(True)
        self.spinBox_PatternNumber.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_PatternNumber.setMaximum(100000)
        self.spinBox_PatternNumber.setObjectName("spinBox_PatternNumber")
        self.horizontalLayout_3.addWidget(self.spinBox_PatternNumber)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget_fileList = QtWidgets.QListWidget(self.frame_2)
        self.listWidget_fileList.setObjectName("listWidget_fileList")
        self.horizontalLayout_2.addWidget(self.listWidget_fileList)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.horizontalLayout_11.addWidget(self.groupBox_3)
        self.frame_19 = QtWidgets.QFrame(self.frame_12)
        self.frame_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.frame_19)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)

        # First Plot - was changed here but can be done in QT designer. Wrong widget!!!
        # self.graphicsView_rawPattern = QtWidgets.QGraphicsView(self.frame_19)
        # self.graphicsView_rawPattern.setObjectName("graphicsView_rawPattern")
        # self.verticalLayout_7.addWidget(self.graphicsView_rawPattern)
        self.widget_rawPattern = QtWidgets.QWidget(self.frame_19)
        self.widget_rawPattern.setObjectName("widget_rawPattern")
        self.verticalLayout_7.addWidget(self.widget_rawPattern)
        # Add layout to placeholder
        self.verticalLayout_rawPattern = QtWidgets.QVBoxLayout(self.widget_rawPattern)
        self.verticalLayout_rawPattern.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_rawPattern.setSpacing(0)
        self.verticalLayout_rawPattern.setObjectName("verticalLayout_rawPattern")

        self.horizontalLayout_11.addWidget(self.frame_19)
        self.verticalLayout_9.addWidget(self.frame_12)
        self.frame_17 = QtWidgets.QFrame(self.centralwidget)
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_14 = QtWidgets.QFrame(self.frame_17)
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_16)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_20.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.frame_24 = QtWidgets.QFrame(self.groupBox_5)
        self.frame_24.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_29 = QtWidgets.QFrame(self.frame_24)
        self.frame_29.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_13.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_13.setSpacing(12)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_32 = QtWidgets.QFrame(self.frame_29)
        self.frame_32.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_25.setContentsMargins(9, 6, 9, 6)
        self.horizontalLayout_25.setSpacing(12)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.checkBox_ALSfit = QtWidgets.QCheckBox(self.frame_32)
        self.checkBox_ALSfit.setTristate(False)
        self.checkBox_ALSfit.setObjectName("checkBox_ALSfit")
        self.horizontalLayout_25.addWidget(self.checkBox_ALSfit)
        self.checkBox_polyFit = QtWidgets.QCheckBox(self.frame_32)
        self.checkBox_polyFit.setObjectName("checkBox_polyFit")
        self.horizontalLayout_25.addWidget(self.checkBox_polyFit)
        # 'Subtract BG' lives with the BG-method checkboxes
        # (moved here from the Data panel; Recalculate BG stays there).
        self.checkBox_subtractBG = QtWidgets.QCheckBox(self.frame_32)
        self.checkBox_subtractBG.setObjectName("checkBox_subtractBG")
        self.horizontalLayout_25.addWidget(self.checkBox_subtractBG)
        self.verticalLayout_13.addWidget(self.frame_32)
        self.frame_33 = QtWidgets.QFrame(self.frame_29)
        self.frame_33.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_14.setContentsMargins(9, 6, 9, 6)
        self.verticalLayout_14.setSpacing(12)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_28 = QtWidgets.QFrame(self.frame_33)
        self.frame_28.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(12)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_18 = QtWidgets.QLabel(self.frame_28)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_22.addWidget(self.label_18)

        # Updated Spin Box
        self.doubleSpinBox_ALS_lam = QtWidgets.QDoubleSpinBox(self.frame_28)
        self.doubleSpinBox_ALS_lam.setDecimals(3)
        self.doubleSpinBox_ALS_lam.setMinimum(0.001)
        self.doubleSpinBox_ALS_lam.setMaximum(1000.0)
        self.doubleSpinBox_ALS_lam.setSingleStep(0.1)
        self.doubleSpinBox_ALS_lam.setProperty("value", 10.0)
        self.doubleSpinBox_ALS_lam.setObjectName("doubleSpinBox_ALS_lam")

        self.horizontalLayout_22.addWidget(self.doubleSpinBox_ALS_lam)
        self.verticalLayout_14.addWidget(self.frame_28)
        self.frame_30 = QtWidgets.QFrame(self.frame_33)
        self.frame_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(12)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_19 = QtWidgets.QLabel(self.frame_30)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_23.addWidget(self.label_19)

        # Updated Spin Box
        self.doubleSpinBox_ALS_p = QtWidgets.QDoubleSpinBox(self.frame_30)
        self.doubleSpinBox_ALS_p.setDecimals(3)
        self.doubleSpinBox_ALS_p.setMaximum(10)
        self.doubleSpinBox_ALS_p.setSingleStep(0.005)
        self.doubleSpinBox_ALS_p.setProperty("value", 0.040)
        self.doubleSpinBox_ALS_p.setObjectName("doubleSpinBox_ALS_p")

        self.horizontalLayout_23.addWidget(self.doubleSpinBox_ALS_p)
        self.verticalLayout_14.addWidget(self.frame_30)
        self.frame_31 = QtWidgets.QFrame(self.frame_33)
        self.frame_31.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(12)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_20 = QtWidgets.QLabel(self.frame_31)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_24.addWidget(self.label_20)

        # Updated Spin Box
        self.doubleSpinBox_ALS_niter = QtWidgets.QDoubleSpinBox(self.frame_31)
        self.doubleSpinBox_ALS_niter.setObjectName("doubleSpinBox_ALS_niter")
        self.horizontalLayout_24.addWidget(self.doubleSpinBox_ALS_niter)
        self.doubleSpinBox_ALS_niter.setDecimals(0)
        self.doubleSpinBox_ALS_niter.setMaximum(5000)
        self.doubleSpinBox_ALS_niter.setSingleStep(10)
        self.doubleSpinBox_ALS_niter.setProperty("value", 100)

        self.verticalLayout_14.addWidget(self.frame_31)
        self.verticalLayout_13.addWidget(self.frame_33)
        self.verticalLayout_11.addWidget(self.frame_29)
        self.horizontalLayout_20.addWidget(self.frame_24)
        self.frame_25 = QtWidgets.QFrame(self.groupBox_5)
        self.frame_25.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_10.setContentsMargins(9, 6, 9, 6)
        self.verticalLayout_10.setSpacing(12)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_3 = QtWidgets.QFrame(self.frame_25)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(12)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.spinBox_BG_Order = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_BG_Order.setProperty("value", 5)
        self.spinBox_BG_Order.setObjectName("spinBox_BG_Order")
        self.horizontalLayout_4.addWidget(self.spinBox_BG_Order)
        self.verticalLayout_10.addWidget(self.frame_3)
        self.frame_7 = QtWidgets.QFrame(self.frame_25)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(12)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.doubleSpinBox_BG_Prominence = QtWidgets.QDoubleSpinBox(self.frame_7)
        self.doubleSpinBox_BG_Prominence.setSingleStep(0.01)
        self.doubleSpinBox_BG_Prominence.setProperty("value", 0.08)
        self.doubleSpinBox_BG_Prominence.setObjectName("doubleSpinBox_BG_Prominence")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_BG_Prominence)
        self.verticalLayout_10.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_25)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(12)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.doubleSpinBox_BG_Height = QtWidgets.QDoubleSpinBox(self.frame_8)
        self.doubleSpinBox_BG_Height.setSingleStep(0.1)
        self.doubleSpinBox_BG_Height.setProperty("value", 0.8)
        self.doubleSpinBox_BG_Height.setObjectName("doubleSpinBox_BG_Height")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_BG_Height)
        self.verticalLayout_10.addWidget(self.frame_8)
        self.frame_27 = QtWidgets.QFrame(self.frame_25)
        self.frame_27.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(12)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_16 = QtWidgets.QLabel(self.frame_27)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_19.addWidget(self.label_16)
        self.doubleSpinBox_BG_width = QtWidgets.QDoubleSpinBox(self.frame_27)
        self.doubleSpinBox_BG_width.setMaximum(10.0)
        self.doubleSpinBox_BG_width.setSingleStep(0.01)
        self.doubleSpinBox_BG_width.setProperty("value", 0.3)
        self.doubleSpinBox_BG_width.setObjectName("doubleSpinBox_BG_width")
        self.horizontalLayout_19.addWidget(self.doubleSpinBox_BG_width)
        self.verticalLayout_10.addWidget(self.frame_27)
        self.horizontalLayout_20.addWidget(self.frame_25)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        # ============================================================
        # groupBox_7: "JCPDS files" panel
        # ------------------------------------------------------------
        # Layout as in EXODUS_GUI_placeholders.ui:
        #
        #   groupBox_7  (vertical: verticalLayout_2)
        #     frame_49  (horizontal: horizontalLayout_33)
        #       frame_37  (LEFT column, vertical: verticalLayout_15)
        #         frame_45 -> frame_50 : Load / Fit / Save buttons
        #         frame_43 : peak profile - Gaussian / Pseudo Voigt
        #                    + frame_57 (eta start value)
        #         frame_34 : Difference + Max shift %
        #       tableWidget_JCPDSTable      (SIBLING of frame_37)
        #       widget                      (empty placeholder)
        #     frame_21       (empty placeholder)
        #     frame_58  (horizontal: horizontalLayout_36)
        #       frame_38 -> frame_41 : peak broadening (grid)
        #           column 0 = Fix Sigma / Fix sigma 1/cos(theta) /
        #                      Vary Sigma / Vary by phase
        #           columns 1-2 = Caglioti / U / V / W (label + spin box)
        #       frame_35 -> frame_46 : 4 stacked rows
        #           frame_47 = Amplitude, frame_48 = Amp. Bounds,
        #           frame_40 = Sigma,     frame_39 = Sig. Bounds
        #     frame_22       (empty placeholder)
        #     verticalSpacer
        #
        # The JCPDS table has 8 columns (the 6 in the .ui plus Colour
        # and Edit which are populated dynamically by
        # EXODUS_main.load_jcpds_files()). Show/Use/Start F/End F/
        # Colour/Edit are narrowed for compactness; per-cell checkboxes
        # are centred via EXODUS_main._centered_checkbox().
        # ============================================================
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame_16)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # ============================================================
        # frame_49: horizontal row holding the control column +
        # the JCPDS table + an empty widget placeholder.
        # ============================================================
        self.frame_49 = QtWidgets.QFrame(self.groupBox_7)
        #self.frame_49.setFrameShape(QtWidgets.QFrame.StyledPanel)
        #self.frame_49.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_49.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_49.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_49.setObjectName("frame_49")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame_49)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setSpacing(12)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")

        # ============================================================
        # frame_37: LEFT control column. Vertical stack of:
        #   frame_45 (Load/Fit/Save), frame_35 (spinbox rows),
        #   frame_38 (sigma checkboxes), frame_34 (Difference + Max shift)
        # ============================================================
        self.frame_37 = QtWidgets.QFrame(self.frame_49)
        #self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        #self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_37.setObjectName("frame_37")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_37)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")

        # ---- frame_45 → frame_50: Load JCPDS / Fit JCPDS(s) / Save ----
        self.frame_45 = QtWidgets.QFrame(self.frame_37)
        self.frame_45.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_45.setObjectName("frame_45")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_45)
        self.verticalLayout_20.setContentsMargins(9, 6, 9, 6)
        self.verticalLayout_20.setSpacing(12)
        self.verticalLayout_20.setObjectName("verticalLayout_20")

        self.frame_50 = QtWidgets.QFrame(self.frame_45)
        self.frame_50.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_50.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_50.setObjectName("frame_50")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_50)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(6)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.pushButton_loadJCPDS = QtWidgets.QPushButton(self.frame_50)
        self.pushButton_loadJCPDS.setObjectName("pushButton_loadJCPDS")
        self.verticalLayout_23.addWidget(self.pushButton_loadJCPDS)
        self.pushButton_fitJCPDS_single = QtWidgets.QPushButton(self.frame_50)
        self.pushButton_fitJCPDS_single.setObjectName("pushButton_fitJCPDS_single")
        self.verticalLayout_23.addWidget(self.pushButton_fitJCPDS_single)
        self.pushButton_save_single = QtWidgets.QPushButton(self.frame_50)
        self.pushButton_save_single.setObjectName("pushButton_save_single")
        self.verticalLayout_23.addWidget(self.pushButton_save_single)
        self.verticalLayout_20.addWidget(self.frame_50)
        self.verticalLayout_15.addWidget(self.frame_45)

        # ---- frame_43: peak profile (Gaussian / pseudo-Voigt + eta) ----
        self.frame_43 = QtWidgets.QFrame(self.frame_37)
        self.frame_43.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_43.setObjectName("frame_43")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_43)
        self.verticalLayout_18.setContentsMargins(9, 6, 9, 6)
        self.verticalLayout_18.setSpacing(12)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_43)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_18.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_43)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_18.addWidget(self.checkBox_5)
        self.frame_57 = QtWidgets.QFrame(self.frame_43)
        self.frame_57.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_57.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_57.setObjectName("frame_57")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_57)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(12)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.horizontalLayout_21.addStretch(1)      # eta to the right
        self.label_21 = QtWidgets.QLabel(self.frame_57)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_21.addWidget(self.label_21)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.frame_57)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_21.addWidget(self.doubleSpinBox_2)
        self.verticalLayout_18.addWidget(self.frame_57)
        self.verticalLayout_15.addWidget(self.frame_43)


        # ---- frame_34: Difference checkbox + Max shift % spinbox ----
        self.frame_34 = QtWidgets.QFrame(self.frame_37)
        self.frame_34.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_34.setObjectName("frame_34")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_34)
        self.verticalLayout_21.setContentsMargins(9, 6, 9, 6)
        self.verticalLayout_21.setSpacing(12)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.checkBox_differencePlot = QtWidgets.QCheckBox(self.frame_34)
        self.checkBox_differencePlot.setObjectName("checkBox_differencePlot")
        self.verticalLayout_21.addWidget(self.checkBox_differencePlot)
        self.frame_36 = QtWidgets.QFrame(self.frame_34)
        self.frame_36.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_36)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setSpacing(12)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_17 = QtWidgets.QLabel(self.frame_36)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_26.addWidget(self.label_17)
        self.doubleSpinBox_maxShiftFit = QtWidgets.QDoubleSpinBox(self.frame_36)
        self.doubleSpinBox_maxShiftFit.setMaximum(2.0)
        self.doubleSpinBox_maxShiftFit.setSingleStep(0.05)
        self.doubleSpinBox_maxShiftFit.setProperty("value", 1.0)
        self.doubleSpinBox_maxShiftFit.setObjectName("doubleSpinBox_maxShiftFit")
        self.horizontalLayout_26.addWidget(self.doubleSpinBox_maxShiftFit)
        self.verticalLayout_21.addWidget(self.frame_36)
        self.verticalLayout_15.addWidget(self.frame_34)

        # frame_37 done — add it to the top row.
        self.horizontalLayout_33.addWidget(self.frame_37)

        # ============================================================
        # tableWidget_JCPDSTable: sibling of frame_37 inside frame_49.
        # 8 columns are kept (the 6 specified in the .ui plus Colour +
        # Edit, populated dynamically by load_jcpds_files()):
        #   col 0 JCPDS    : stretches (auto)
        #   col 1 Show     : fixed 30 px (centred checkbox)
        #   col 2 Use      : fixed 30 px (centred checkbox)
        #   col 3 Pressure : resize-to-contents
        #   col 4 Start F  : fixed 55 px
        #   col 5 End F    : fixed 55 px
        #   col 6 Colour   : fixed 36 px
        #   col 7 Edit     : fixed 40 px
        # ============================================================
        self.tableWidget_JCPDSTable = QtWidgets.QTableWidget(self.frame_49)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget_JCPDSTable.setFont(font)
        self.tableWidget_JCPDSTable.setStyleSheet("")
        self.tableWidget_JCPDSTable.setObjectName("tableWidget_JCPDSTable")
        self.tableWidget_JCPDSTable.setColumnCount(8)
        self.tableWidget_JCPDSTable.setRowCount(0)
        for _col in range(8):
            self.tableWidget_JCPDSTable.setHorizontalHeaderItem(
                _col, QtWidgets.QTableWidgetItem())

        _hdr = self.tableWidget_JCPDSTable.horizontalHeader()
        # All columns use Interactive mode so the user can drag-resize
        # any column divider. The initial widths below are starting
        # points; everything is freely user-adjustable from there.
        # The "last section stretch" trick is OFF (so col 7 keeps its
        # fixed look) but col 0 (JCPDS name) is widened so it absorbs
        # any leftover horizontal space initially.
        for _col in range(8):
            _hdr.setSectionResizeMode(_col, QtWidgets.QHeaderView.Interactive)
        _hdr.setStretchLastSection(False)
        # Starting column widths (drag-resizable from here).
        self.tableWidget_JCPDSTable.setColumnWidth(0, 180)   # JCPDS name
        self.tableWidget_JCPDSTable.setColumnWidth(1, 30)    # Show (centred checkbox)
        self.tableWidget_JCPDSTable.setColumnWidth(2, 30)    # Use  (centred checkbox)
        self.tableWidget_JCPDSTable.setColumnWidth(3, 100)    # Pressure
        self.tableWidget_JCPDSTable.setColumnWidth(4, 100)    # Start F (room for 5-digit frame nos)
        self.tableWidget_JCPDSTable.setColumnWidth(5, 100)    # End F   (same)
        self.tableWidget_JCPDSTable.setColumnWidth(6, 36)    # Colour
        self.tableWidget_JCPDSTable.setColumnWidth(7, 50)    # Edit
        self.tableWidget_JCPDSTable.verticalHeader().setDefaultSectionSize(22)
        self.tableWidget_JCPDSTable.verticalHeader().setVisible(False)

        self.horizontalLayout_33.addWidget(self.tableWidget_JCPDSTable)

        # ============================================================
        # widget: empty placeholder kept for layout parity with the .ui
        # (its verticalLayout_22 is referenced as a sibling of the
        # table inside frame_49).
        # ============================================================
        self.widget = QtWidgets.QWidget(self.frame_49)
        self.widget.setObjectName("widget")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_33.addWidget(self.widget)

        # Give the table all the horizontal stretch; the control column
        # and the empty placeholder hug their natural width.
        self.horizontalLayout_33.setStretch(0, 0)   # frame_37
        self.horizontalLayout_33.setStretch(1, 1)   # tableWidget
        self.horizontalLayout_33.setStretch(2, 0)   # widget

        self.verticalLayout_2.addWidget(self.frame_49)

        # ---- Three empty placeholder rows from the .ui spec ----
        self.frame_21 = QtWidgets.QFrame(self.groupBox_7)
        self.frame_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(8)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_2.addWidget(self.frame_21)

        # ============================================================
        # frame_58: row below the JCPDS table with the peak-broadening
        # options (frame_38) next to the amplitude / sigma start values
        # (frame_35), as in EXODUS_GUI_placeholders.ui.
        # ============================================================
        self.frame_58 = QtWidgets.QFrame(self.groupBox_7)
        self.frame_58.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_58.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_58.setObjectName("frame_58")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.frame_58)
        self.horizontalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")

        # frame_38 (left): peak broadening, mutually exclusive checkboxes
        self.frame_38 = QtWidgets.QFrame(self.frame_58)
        self.frame_38.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_38.setObjectName("frame_38")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_38)
        self.verticalLayout_16.setContentsMargins(9, 6, 9, 6)
        self.verticalLayout_16.setSpacing(12)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        # frame_41: one grid, so both columns share the same rows; the four
        # rows have equal stretch and fill the box height (aligned with the
        # Amplitude / Sigma rows of frame_35 next to it):
        #   row 0: Fix Sigma              | Caglioti (spans columns 1-3)
        #   row 1: Fix sigma 1/cos(theta) | U  [spin box]
        #   row 2: Vary Sigma             | V  [spin box]
        #   row 3: Vary by phase          | W  [spin box]
        # Column 3 is empty and takes up the remaining width.
        self.frame_41 = QtWidgets.QFrame(self.frame_38)
        self.frame_41.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.gridLayout_41 = QtWidgets.QGridLayout(self.frame_41)
        self.gridLayout_41.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_41.setHorizontalSpacing(24)
        self.gridLayout_41.setVerticalSpacing(6)
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.checkBox_fixSigma_2 = QtWidgets.QCheckBox(self.frame_41)
        self.checkBox_fixSigma_2.setObjectName("checkBox_fixSigma_2")
        self.gridLayout_41.addWidget(self.checkBox_fixSigma_2, 0, 0)
        self.checkBox = QtWidgets.QCheckBox(self.frame_41)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_41.addWidget(self.checkBox, 1, 0)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_41)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_41.addWidget(self.checkBox_2, 2, 0)
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_41)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_41.addWidget(self.checkBox_3, 3, 0)
        self.checkBox_4_Caglioti = QtWidgets.QCheckBox(self.frame_41)
        self.checkBox_4_Caglioti.setObjectName("checkBox_4_Caglioti")
        self.gridLayout_41.addWidget(self.checkBox_4_Caglioti, 0, 1, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.frame_41)
        self.label_8.setObjectName("label_8")
        self.gridLayout_41.addWidget(self.label_8, 1, 1)
        self.doubleSpinBox_5_CagliotiU = QtWidgets.QDoubleSpinBox(self.frame_41)
        self.doubleSpinBox_5_CagliotiU.setObjectName("doubleSpinBox_5_CagliotiU")
        self.gridLayout_41.addWidget(self.doubleSpinBox_5_CagliotiU, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.frame_41)
        self.label_13.setObjectName("label_13")
        self.gridLayout_41.addWidget(self.label_13, 2, 1)
        self.doubleSpinBox_2_CagliotiV = QtWidgets.QDoubleSpinBox(self.frame_41)
        self.doubleSpinBox_2_CagliotiV.setObjectName("doubleSpinBox_2_CagliotiV")
        self.gridLayout_41.addWidget(self.doubleSpinBox_2_CagliotiV, 2, 2)
        self.label_14 = QtWidgets.QLabel(self.frame_41)
        self.label_14.setObjectName("label_14")
        self.gridLayout_41.addWidget(self.label_14, 3, 1)
        self.doubleSpinBox_4__CagliotiW = QtWidgets.QDoubleSpinBox(self.frame_41)
        self.doubleSpinBox_4__CagliotiW.setObjectName("doubleSpinBox_4__CagliotiW")
        self.gridLayout_41.addWidget(self.doubleSpinBox_4__CagliotiW, 3, 2)
        for row in range(4):
            self.gridLayout_41.setRowStretch(row, 1)
        self.gridLayout_41.setColumnStretch(3, 1)
        self.equalise_broadening_rows()
        self.verticalLayout_16.addWidget(self.frame_41)
        self.horizontalLayout_36.addWidget(self.frame_38)

        # frame_35 (right): four stacked label + spin-box rows
        self.frame_35 = QtWidgets.QFrame(self.frame_58)
        self.frame_35.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")

        self.frame_46 = QtWidgets.QFrame(self.frame_35)
        self.frame_46.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_46.setObjectName("frame_46")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_46)
        self.verticalLayout_28.setContentsMargins(9, 6, 9, 6)
        self.verticalLayout_28.setSpacing(12)
        self.verticalLayout_28.setObjectName("verticalLayout_28")

        # frame_47: Amplitude row
        self.frame_47 = QtWidgets.QFrame(self.frame_46)
        self.frame_47.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_47.setObjectName("frame_47")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.frame_47)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setSpacing(12)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_11 = QtWidgets.QLabel(self.frame_47)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_31.addWidget(self.label_11)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame_47)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_31.addWidget(self.doubleSpinBox)
        self.verticalLayout_28.addWidget(self.frame_47)

        # frame_48: Amp. Bounds row
        self.frame_48 = QtWidgets.QFrame(self.frame_46)
        self.frame_48.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_48.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_48.setObjectName("frame_48")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.frame_48)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setSpacing(12)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_22 = QtWidgets.QLabel(self.frame_48)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_32.addWidget(self.label_22)
        self.doubleSpinBox_fitAmpGuess = QtWidgets.QDoubleSpinBox(self.frame_48)
        self.doubleSpinBox_fitAmpGuess.setDecimals(3)
        self.doubleSpinBox_fitAmpGuess.setSingleStep(0.1)
        self.doubleSpinBox_fitAmpGuess.setProperty("value", 1.0)
        self.doubleSpinBox_fitAmpGuess.setObjectName("doubleSpinBox_fitAmpGuess")
        self.horizontalLayout_32.addWidget(self.doubleSpinBox_fitAmpGuess)
        self.verticalLayout_28.addWidget(self.frame_48)

        # frame_40: Sigma row
        self.frame_40 = QtWidgets.QFrame(self.frame_46)
        self.frame_40.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frame_40)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setSpacing(12)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_12 = QtWidgets.QLabel(self.frame_40)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_30.addWidget(self.label_12)
        self.doubleSpinBox_fitSigGuess = QtWidgets.QDoubleSpinBox(self.frame_40)
        self.doubleSpinBox_fitSigGuess.setDecimals(3)
        self.doubleSpinBox_fitSigGuess.setSingleStep(0.001)
        self.doubleSpinBox_fitSigGuess.setProperty("value", 0.020)
        self.doubleSpinBox_fitSigGuess.setObjectName("doubleSpinBox_fitSigGuess")
        self.horizontalLayout_30.addWidget(self.doubleSpinBox_fitSigGuess)
        self.verticalLayout_28.addWidget(self.frame_40)

        # frame_39: Sig. Bounds row
        self.frame_39 = QtWidgets.QFrame(self.frame_46)
        self.frame_39.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_39)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setSpacing(12)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_23 = QtWidgets.QLabel(self.frame_39)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_29.addWidget(self.label_23)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.frame_39)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.horizontalLayout_29.addWidget(self.doubleSpinBox_3)
        self.verticalLayout_28.addWidget(self.frame_39)

        self.horizontalLayout_27.addWidget(self.frame_46)
        self.horizontalLayout_36.addWidget(self.frame_35)
        self.horizontalLayout_36.setStretch(0, 1)     # both boxes equally wide
        self.horizontalLayout_36.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.frame_58)

        self.frame_22 = QtWidgets.QFrame(self.groupBox_7)
        self.frame_22.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_2.addWidget(self.frame_22)

        verticalSpacer_jcpds = QtWidgets.QSpacerItem(
            20, 40,
            QtWidgets.QSizePolicy.Minimum,
            QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(verticalSpacer_jcpds)

        self.verticalLayout_5.addWidget(self.groupBox_7)
        self.horizontalLayout_14.addWidget(self.frame_16)
        self.frame_18 = QtWidgets.QFrame(self.frame_14)
        self.frame_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.frame_18)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)

        # Second Plot - was changed here but can be done in QT designer. Wrong widget!!!
        # self.graphicsView_processedPattern = QtWidgets.QGraphicsView(self.frame_18)
        # self.graphicsView_processedPattern.setObjectName("graphicsView_processedPattern")
        # self.verticalLayout_6.addWidget(self.graphicsView_processedPattern)
        # Create a placeholder QWidget in your frame
        self.widget_processedPattern = QtWidgets.QWidget(self.frame_18)
        self.widget_processedPattern.setObjectName("widget_processedPattern")  # corrected name
        # Add a vertical layout to this placeholder
        self.verticalLayout_processedPattern = QtWidgets.QVBoxLayout(self.widget_processedPattern)
        self.verticalLayout_processedPattern.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_processedPattern.setSpacing(0)
        self.verticalLayout_processedPattern.setObjectName("verticalLayout_processedPattern")  # corrected name
        # Add the placeholder widget to your parent layout
        self.verticalLayout_6.addWidget(self.widget_processedPattern)
        self.horizontalLayout_14.addWidget(self.frame_18)

        self.horizontalLayout_14.addWidget(self.frame_18)
        self.frame_15 = QtWidgets.QFrame(self.frame_14)
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_14.addWidget(self.frame_15)
        self.horizontalLayout_12.addWidget(self.frame_14)
        self.verticalLayout_9.addWidget(self.frame_17)
        self.frame_13 = QtWidgets.QFrame(self.centralwidget)
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        # ============================================================
        # groupBox_4: "2D Plot and Fits" panel
        # Layout (per backup2_bak.ui):
        #   verticalLayout_4
        #     frame_55 (HBox: horizontalLayout_35)
        #       frame_54 (VBox: verticalLayout_26)
        #         frame_51 (Sunken Box, VBox: verticalLayout_24)
        #           frame_9  : checkBox_sequential
        #           frame_10 : checkBox_pressureWalk + Delta P + doubleSpinBox_7
        #           frame_6  : checkBox_poressureGuess
        #         frame_52 (Sunken Box, VBox: verticalLayout_25)
        #           pushButton_fitAll  ("Fit all")
        #           pushButton_saveAll ("Save All")
        #           pushButton_save2D  ("Save 2D Plot")  [was pushButton_stopAll in .ui]
        #       frame_53 (HBox: horizontalLayout_34)
        #         frame_26 (VBox: verticalLayout_12)
        #           pushButton_2 ("+"), pushButton ("-"), pushButton_3 ("x") + spacer
        #         tableWidget_PressureGuessTable
        #       frame_56 (VBox: verticalLayout_27)
        #         pushButton_4 ("Lin"), pushButton_5 ("Log"), pushButton_6 ("SQRT"),
        #         spacer, pushButton_7 ("Colour")
        #     frame_11 (empty placeholder, HBox: horizontalLayout_10)
        #     verticalSpacer_2
        # ============================================================
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_13)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_4.setSpacing(12)

        # ---- frame_55: outer 3-column horizontal container ----
        self.frame_55 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_55.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_55.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_55.setObjectName("frame_55")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.frame_55)
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_35.setSpacing(12)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")

        # ---- frame_54: left column (vertical: frame_51 over frame_52) ----
        self.frame_54 = QtWidgets.QFrame(self.frame_55)
        self.frame_54.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_54.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_54.setObjectName("frame_54")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_54)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(12)

        # ---- frame_51: Sunken Box holding the three fit-mode rows ----
        self.frame_51 = QtWidgets.QFrame(self.frame_54)
        self.frame_51.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_51.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_51.setObjectName("frame_51")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_51)
        self.verticalLayout_24.setContentsMargins(9, 6, 9, 6)
        self.verticalLayout_24.setSpacing(12)
        self.verticalLayout_24.setObjectName("verticalLayout_24")

        # frame_9: Sequential Fitting
        self.frame_9 = QtWidgets.QFrame(self.frame_51)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(12)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_sequential = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox_sequential.setObjectName("checkBox_sequential")
        self.horizontalLayout_8.addWidget(self.checkBox_sequential)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_24.addWidget(self.frame_9)

        # frame_10: Pressure Walk + Delta P spinbox
        self.frame_10 = QtWidgets.QFrame(self.frame_51)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(12)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_pressureWalk = QtWidgets.QCheckBox(self.frame_10)
        self.checkBox_pressureWalk.setObjectName("checkBox_pressureWalk")
        self.horizontalLayout_9.addWidget(self.checkBox_pressureWalk)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.label_15 = QtWidgets.QLabel(self.frame_10)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.frame_10)
        self.doubleSpinBox_7.setDecimals(1)
        self.doubleSpinBox_7.setSingleStep(0.5)
        self.doubleSpinBox_7.setProperty("value", 0.5)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_7)
        self.verticalLayout_24.addWidget(self.frame_10)

        # frame_6: Pressure Guess
        self.frame_6 = QtWidgets.QFrame(self.frame_51)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(12)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_poressureGuess = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_poressureGuess.setObjectName("checkBox_poressureGuess")
        self.horizontalLayout_7.addWidget(self.checkBox_poressureGuess)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.verticalLayout_24.addWidget(self.frame_6)

        self.verticalLayout_26.addWidget(self.frame_51)

        # ---- frame_60: row that holds frame_52 (Fit/Save) next to
        #      frame_61 (analysis pop-ups) ----
        self.frame_60 = QtWidgets.QFrame(self.frame_54)
        self.frame_60.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_60.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_60.setObjectName("frame_60")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.frame_60)
        self.horizontalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")

        # ---- frame_52: Sunken Box holding Fit All / Save All / Save 2D Plot ----
        self.frame_52 = QtWidgets.QFrame(self.frame_60)
        self.frame_52.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_52.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_52.setObjectName("frame_52")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_52)
        self.verticalLayout_25.setContentsMargins(9, 6, 9, 6)
        self.verticalLayout_25.setSpacing(12)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.pushButton_fitAll = QtWidgets.QPushButton(self.frame_52)
        self.pushButton_fitAll.setObjectName("pushButton_fitAll")
        self.verticalLayout_25.addWidget(self.pushButton_fitAll)
        self.pushButton_saveAll = QtWidgets.QPushButton(self.frame_52)
        self.pushButton_saveAll.setObjectName("pushButton_saveAll")
        self.verticalLayout_25.addWidget(self.pushButton_saveAll)
        # The .ui file calls this pushButton_stopAll, but per request it
        # keeps the name pushButton_save2D so the existing
        # save_2d_plot connection in EXODUS_main.py keeps working.
        self.pushButton_save2D = QtWidgets.QPushButton(self.frame_52)
        self.pushButton_save2D.setObjectName("pushButton_save2D")
        self.verticalLayout_25.addWidget(self.pushButton_save2D)
        self.horizontalLayout_38.addWidget(self.frame_52)

        # ---- frame_61: Sunken Box with the placeholder buttons for
        #      functionality planned for later versions (Plot Data /
        #      EoS Fit / Stress-Strain). Wired to a "not implemented yet"
        #      notice in EXODUS_main until the features exist. ----
        self.frame_61 = QtWidgets.QFrame(self.frame_60)
        self.frame_61.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_61.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_61.setObjectName("frame_61")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.frame_61)
        self.verticalLayout_39.setContentsMargins(9, 6, 9, 6)
        self.verticalLayout_39.setSpacing(12)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.pushButton_9_plotData = QtWidgets.QPushButton(self.frame_61)
        self.pushButton_9_plotData.setObjectName("pushButton_9_plotData")
        self.verticalLayout_39.addWidget(self.pushButton_9_plotData)
        self.pushButton_10_EoSFit = QtWidgets.QPushButton(self.frame_61)
        self.pushButton_10_EoSFit.setObjectName("pushButton_10_EoSFit")
        self.verticalLayout_39.addWidget(self.pushButton_10_EoSFit)
        self.pushButton_8_stressStrain = QtWidgets.QPushButton(self.frame_61)
        self.pushButton_8_stressStrain.setObjectName("pushButton_8_stressStrain")
        self.verticalLayout_39.addWidget(self.pushButton_8_stressStrain)
        self.horizontalLayout_38.addWidget(self.frame_61)

        self.verticalLayout_26.addWidget(self.frame_60)
        self.horizontalLayout_35.addWidget(self.frame_54)

        # ---- frame_53: middle column (row buttons +/-/x and the table) ----
        self.frame_53 = QtWidgets.QFrame(self.frame_55)
        self.frame_53.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_53.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_53.setObjectName("frame_53")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.frame_53)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")

        # frame_26: vertical column of +/-/x buttons next to the table
        self.frame_26 = QtWidgets.QFrame(self.frame_53)
        self.frame_26.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_26)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_12.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.frame_26)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_12.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_26)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_12.addWidget(self.pushButton_3)
        spacerItem_v3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem_v3)
        self.horizontalLayout_34.addWidget(self.frame_26)

        # The pressure-guess tab widget. Named "tabWidget" to match the
        # prototype layout in backup3.ui. One tab per phase that is
        # marked "Use" in the JCPDS table; tabs are added/removed
        # dynamically by EXODUS_main._rebuild_pressure_guess_tabs().
        # Each tab holds a QTableWidget with columns [Frame, Pressure,
        # Fix].
        #
        # We pre-create one "template" tab + table here so the widget
        # has a sensible initial size from the geometry hint below.
        # On the first rebuild the template is replaced by the live
        # per-phase tabs.
        self.tabWidget = QtWidgets.QTabWidget(self.frame_53)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidget.setMinimumSize(QtCore.QSize(240, 200))

        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")

        self.tableWidget_PressureGuessTable = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_PressureGuessTable.setGeometry(QtCore.QRect(-5, 0, 241, 191))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget_PressureGuessTable.setFont(font)
        self.tableWidget_PressureGuessTable.setObjectName("tableWidget_PressureGuessTable")
        self.tableWidget_PressureGuessTable.setColumnCount(3)
        self.tableWidget_PressureGuessTable.setRowCount(0)
        for i, hdr in enumerate(("Frame", "Pressure", "Fix")):
            it = QtWidgets.QTableWidgetItem()
            it.setText(hdr)
            self.tableWidget_PressureGuessTable.setHorizontalHeaderItem(i, it)

        self.tabWidget.addTab(self.tab, "Tab 1")
        self.horizontalLayout_34.addWidget(self.tabWidget)

        self.horizontalLayout_35.addWidget(self.frame_53)

        # ---- frame_56: right column (Lin / Log / SQRT  +  Colour) ----
        self.frame_56 = QtWidgets.QFrame(self.frame_55)
        self.frame_56.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_56.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_56.setObjectName("frame_56")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_56)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_56)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_27.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_56)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_27.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_56)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_27.addWidget(self.pushButton_6)
        spacerItem_v4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_27.addItem(spacerItem_v4)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_56)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_27.addWidget(self.pushButton_7)
        self.horizontalLayout_35.addWidget(self.frame_56)

        self.verticalLayout_4.addWidget(self.frame_55)

        # ---- frame_11: empty placeholder (kept for layout parity with .ui) ----
        # (frame_11 + horizontalLayout_10 are kept for parity with the
        # .ui file.)
        self.frame_11 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(12)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_4.addWidget(self.frame_11)

        spacerItem8 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.horizontalLayout_13.addWidget(self.groupBox_4)
        self.frame_20 = QtWidgets.QFrame(self.frame_13)
        self.frame_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_8.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.frame_20)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)

        # self.graphicsView_2Dplot = QtWidgets.QGraphicsView(self.frame_20)
        # self.graphicsView_2Dplot.setObjectName("graphicsView_2Dplot")
        # self.verticalLayout_8.addWidget(self.graphicsView_2Dplot)
        # self.horizontalLayout_13.addWidget(self.frame_20)


        # # Third plot and 2D plot
        # # self.graphicsView_2Dplot = QtWidgets.QGraphicsView(self.frame_20)
        # 1. Frame container
        # --- Step 1: Frame and layout (same as yours) ---
        # --- 1. Frame container ---
        self.frame_20 = QtWidgets.QFrame(self.centralwidget)
        self.frame_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_20.setSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                    QtWidgets.QSizePolicy.Expanding)

        # --- 2. Vertical layout inside frame ---
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(2)

        # --- 3. PlotWidget + ImageItem ---
        self.plotWidget_2D = pg.PlotWidget()
        self.plotWidget_2D.setSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                         QtWidgets.QSizePolicy.Expanding)

        self.img_item = pg.ImageItem()
        self.plotWidget_2D.addItem(self.img_item)

        # Add PlotWidget first (it will expand)
        self.verticalLayout_8.addWidget(self.plotWidget_2D)

        # --- 4. LUT horizontal on top (Dioptas style, see lut_toolbox) ---
        self.lut_widget = lut_toolbox.DioptasLUTWidget(image=self.img_item)
        self.verticalLayout_8.insertWidget(0, self.lut_widget)
        # small gap so the LUT never touches / overlaps the 2D plot
        self.verticalLayout_8.insertSpacing(1, 8)

        # --- 5. Add frame to main layout ---
        self.horizontalLayout_13.addWidget(self.frame_20)




        self.verticalLayout_9.addWidget(self.frame_13)
        self.frame_23 = QtWidgets.QFrame(self.centralwidget)
        self.frame_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_9.addWidget(self.frame_23)

        self._build_resizable_layout()
        MainWindow.setCentralWidget(self.centralwidget)
        # Status bar kept (it's part of the standard MainWindow chrome)
        # but the "Files" menubar has been removed to match the new layout.
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # ------------------------------------------------------------------
    # resizable panels
    # ------------------------------------------------------------------
    @staticmethod
    def _remove_trailing_spacer(layout):
        """Remove the last item of `layout` if it is a spacer, so spare
        height goes to the real content instead of empty space."""
        n = layout.count()
        if n and layout.itemAt(n - 1).spacerItem() is not None:
            layout.takeAt(n - 1)

    def _scroll_pane(self, panel, name):
        """Wrap a control panel in a frameless QScrollArea so the splitter
        can shrink it below its natural height (it scrolls instead).
        The minimum WIDTH is pinned to the panel's own, so the left column
        never gets narrower than its contents (no sideways scrolling)."""
        sa = QtWidgets.QScrollArea(self.centralwidget)
        sa.setObjectName(name)
        sa.setWidgetResizable(True)
        sa.setFrameShape(QtWidgets.QFrame.NoFrame)
        sa.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        sa.setWidget(panel)
        sb_w = sa.verticalScrollBar().sizeHint().width()
        sa.setMinimumWidth(panel.minimumSizeHint().width() + sb_w)
        sa.setMinimumHeight(60)
        return sa

    def _build_resizable_layout(self):
        """Re-arrange the three fixed-height rows into two columns of
        splitters so every panel can be resized vertically.

        The .ui file defines three rows:
            frame_12 : [groupBox_3 (Data)          | frame_19 (Raw pattern)]
            frame_17 : [frame_16 (BG + JCPDS)      | frame_18 (Pattern)    ]
            frame_13 : [groupBox_4 (2D Plot/Fits)  | frame_20 (2D plot)    ]
        Every row is as tall as its taller half, so nothing could be
        resized independently - the left-hand controls set a hard minimum
        height per row, which is why a splitter dropped straight into
        verticalLayout_9 can't work.

        After:
            splitter_main (horizontal)
              splitter_controls (vertical):  Data | BG Subtraction |
                                             JCPDS files | 2D Plot and Fits
                  (each in a scroll area, so it can shrink and scroll)
              splitter_plots (vertical):     Raw | Pattern | 2D plot
        All widget names are unchanged, so EXODUS_main needs no changes.
        """
        # 1. Detach the blocks from their row layouts
        self.horizontalLayout_11.removeWidget(self.groupBox_3)
        self.horizontalLayout_11.removeWidget(self.frame_19)
        self.verticalLayout_5.removeWidget(self.groupBox_5)
        self.verticalLayout_5.removeWidget(self.groupBox_7)
        self.horizontalLayout_14.removeWidget(self.frame_16)
        self.horizontalLayout_14.removeWidget(self.frame_18)
        self.horizontalLayout_13.removeWidget(self.groupBox_4)
        self.horizontalLayout_13.removeWidget(self.frame_20)

        # 2. Retire the (now empty) containers
        for w in (self.frame_12, self.frame_17, self.frame_13, self.frame_23):
            self.verticalLayout_9.removeWidget(w)
            w.hide()
        self.frame_16.hide()

        # 3. Spare height should go to the JCPDS table and the
        #    pressure-guess tabs, not to the trailing spacers.
        self._remove_trailing_spacer(self.verticalLayout_2)   # JCPDS files
        self._remove_trailing_spacer(self.verticalLayout_4)   # 2D Plot and Fits

        # Splitter handles: use the plain Fusion handle (small grip dash),
        # the same as in the pop-up windows. The broad grey/green styled
        # handles are switched off below (kept commented for reference).
        # handle_qss = ("QSplitter::handle { background-color: rgb(80, 80, 80); } "
        #               "QSplitter::handle:hover { background-color: rgb(46, 204, 113); }")

        # 4. Left column: vertical splitter with the four control panels
        self.splitter_controls = QtWidgets.QSplitter(QtCore.Qt.Vertical, self.centralwidget)
        self.splitter_controls.setObjectName("splitter_controls")
        self.splitter_controls.setChildrenCollapsible(False)
        # self.splitter_controls.setHandleWidth(7)
        self._control_panels = (self.groupBox_3, self.groupBox_5,
                                self.groupBox_7, self.groupBox_4)
        names = ("scroll_data", "scroll_bg", "scroll_jcpds", "scroll_fits")
        for panel, nm in zip(self._control_panels, names):
            self.splitter_controls.addWidget(self._scroll_pane(panel, nm))
        # Panes that should absorb spare height (file list, JCPDS table)
        self._controls_grow = (0, 2)
        for i in range(4):
            self.splitter_controls.setStretchFactor(i, 1 if i in self._controls_grow else 0)
        # self.splitter_controls.setStyleSheet(handle_qss)
        self.leftColumn = self.splitter_controls      # kept for older code

        # 5. Right column: vertical splitter with the three plot panels
        self.splitter_plots = QtWidgets.QSplitter(QtCore.Qt.Vertical, self.centralwidget)
        self.splitter_plots.setObjectName("splitter_plots")
        self.splitter_plots.setChildrenCollapsible(False)
        # self.splitter_plots.setHandleWidth(7)
        for w in (self.frame_19, self.frame_18, self.frame_20):
            # Plots must be allowed to shrink - otherwise the splitter
            # handle refuses to move (pyqtgraph's size hints are large).
            w.setMinimumHeight(90)
            w.setSizePolicy(QtWidgets.QSizePolicy.Expanding,
                            QtWidgets.QSizePolicy.Ignored)
            self.splitter_plots.addWidget(w)
        self.splitter_plots.setStretchFactor(0, 2)
        self.splitter_plots.setStretchFactor(1, 3)
        self.splitter_plots.setStretchFactor(2, 3)
        # self.splitter_plots.setStyleSheet(handle_qss)

        # 6. Horizontal splitter: [controls | plots]
        self.splitter_main = QtWidgets.QSplitter(QtCore.Qt.Horizontal, self.centralwidget)
        self.splitter_main.setObjectName("splitter_main")
        self.splitter_main.setChildrenCollapsible(False)
        # self.splitter_main.setHandleWidth(7)
        self.splitter_main.addWidget(self.splitter_controls)
        self.splitter_main.addWidget(self.splitter_plots)
        self.splitter_main.setStretchFactor(0, 0)
        self.splitter_main.setStretchFactor(1, 1)
        # self.splitter_main.setStyleSheet(handle_qss)

        self.verticalLayout_9.addWidget(self.splitter_main)

    def equalise_broadening_rows(self):
        """Give the four rows of the peak-broadening grid the same height.

        Row stretch only shares out the EXTRA space, on top of each row's
        natural height. Rows 1-3 hold a spin box, which is taller than the
        check box of row 0 on most styles, so row 0 would end up shorter
        (smaller gap Caglioti -> U than U -> V). A common minimum height
        (= tallest widget) makes the rows equal. Called again by
        MainWindow.showEvent, after the style sheet has set the final sizes.
        """
        rowHeight = max(max(wdg.sizeHint().height(),
                            wdg.minimumSizeHint().height(),
                            wdg.minimumHeight()) for wdg in (
            self.checkBox_fixSigma_2, self.checkBox, self.checkBox_2,
            self.checkBox_3, self.checkBox_4_Caglioti,
            self.doubleSpinBox_5_CagliotiU, self.doubleSpinBox_2_CagliotiV,
            self.doubleSpinBox_4__CagliotiW))
        for row in range(4):
            self.gridLayout_41.setRowMinimumHeight(row, rowHeight)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Data "))
        self.pushButton_loadPoni.setText(_translate("MainWindow", "Load Poni"))
        self.label_9.setText(_translate("MainWindow", "Data Range"))
        self.label_10.setText(_translate("MainWindow", "to"))
        self.pushButton_loadFiles.setText(_translate("MainWindow", "Load Files"))
        self.checkBox_subtractBG.setText(_translate("MainWindow", "Subtract BG"))
        self.pushButton_recalculateBG.setText(_translate("MainWindow", "Recalculate BG"))
        self.pushButton_8_deltePattern.setText(_translate("MainWindow", "Remove Pattern"))
        self.label.setText(_translate("MainWindow", " Pattern No. "))
        self.label_6.setText(_translate("MainWindow", "Raw Pattern"))
        self.groupBox_5.setTitle(_translate("MainWindow", "BG Subtraction"))
        self.checkBox_ALSfit.setText(_translate("MainWindow", "ALS Fit"))
        self.checkBox_polyFit.setText(_translate("MainWindow", "Poly Fit"))
        self.label_18.setText(_translate("MainWindow", "Smoothness (×10⁶)"))
        self.label_19.setText(_translate("MainWindow", "Width"))
        self.label_20.setText(_translate("MainWindow", "Iterations"))
        self.label_2.setText(_translate("MainWindow", "Order"))
        self.label_3.setText(_translate("MainWindow", "Prominence"))
        self.label_4.setText(_translate("MainWindow", "Height"))
        self.label_16.setText(_translate("MainWindow", "Width"))
        self.groupBox_7.setTitle(_translate("MainWindow", "JCPDS files "))
        self.pushButton_loadJCPDS.setText(_translate("MainWindow", "Load JCPDS"))
        self.pushButton_fitJCPDS_single.setText(_translate("MainWindow", "Fit JCPDS(s)"))
        self.pushButton_save_single.setText(_translate("MainWindow", "Save"))
        self.checkBox_differencePlot.setText(_translate("MainWindow", "Difference"))
        self.label_17.setText(_translate("MainWindow", "Max shift %"))
        self.label_11.setText(_translate("MainWindow", "Amplitude"))
        self.label_22.setText(_translate("MainWindow", "Amp. Bounds"))
        self.checkBox_fixSigma_2.setText(_translate("MainWindow", "Fix Sigma"))
        self.checkBox.setText(_translate("MainWindow", "Fix sigma 1/cos(θ)"))
        self.checkBox_2.setText(_translate("MainWindow", "Vary Sigma"))
        self.checkBox_3.setText(_translate("MainWindow", "Vary by phase"))
        self.checkBox_4.setText(_translate("MainWindow", "Gaussian"))
        self.checkBox_5.setText(_translate("MainWindow", "Pseudo Voigt"))
        self.label_21.setText(_translate("MainWindow", "\u03b7"))
        self.checkBox_4_Caglioti.setText(_translate(
            "MainWindow", "Caglioti (U tan\u00b2\u03b8 + V tan\u03b8 + W)"))
        self.label_8.setText(_translate("MainWindow", "U"))
        self.label_13.setText(_translate("MainWindow", "V"))
        self.label_14.setText(_translate("MainWindow", "W"))
        self.label_12.setText(_translate("MainWindow", "Sigma"))
        self.label_23.setText(_translate("MainWindow", "Sig. Bounds"))
        item = self.tableWidget_JCPDSTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "JCPDS"))
        item = self.tableWidget_JCPDSTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Show"))
        item = self.tableWidget_JCPDSTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Use"))
        item = self.tableWidget_JCPDSTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Pressure"))
        item = self.tableWidget_JCPDSTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Start F"))
        item = self.tableWidget_JCPDSTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "End F"))
        item = self.tableWidget_JCPDSTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Col."))
        item = self.tableWidget_JCPDSTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Edit"))
        self.label_5.setText(_translate("MainWindow", "Pattern"))
        self.groupBox_4.setTitle(_translate("MainWindow", "2D Plot and Fits "))
        self.checkBox_sequential.setText(_translate("MainWindow", "Sequential Fitting"))
        self.checkBox_pressureWalk.setText(_translate("MainWindow", "Pressure Walk"))
        self.label_15.setText(_translate("MainWindow", "Delta P"))
        self.checkBox_poressureGuess.setText(_translate("MainWindow", "Pressure Guess"))
        self.pushButton_fitAll.setText(_translate("MainWindow", "Fit all"))
        self.pushButton_saveAll.setText(_translate("MainWindow", "Save All"))
        self.pushButton_save2D.setText(_translate("MainWindow", "Save 2D Plot"))
        self.pushButton_9_plotData.setText(_translate("MainWindow", "Plot Data"))
        self.pushButton_10_EoSFit.setText(_translate("MainWindow", "EoS Fit"))
        self.pushButton_8_stressStrain.setText(_translate("MainWindow", "Stress/Strain"))
        # Row buttons next to the Pressure Guess table
        self.pushButton_2.setText(_translate("MainWindow", "+"))
        self.pushButton.setText(_translate("MainWindow", "-"))
        self.pushButton_3.setText(_translate("MainWindow", "x"))
        # Intensity scale + colormap buttons (next to the 2D plot)
        self.pushButton_4.setText(_translate("MainWindow", "Lin"))
        self.pushButton_5.setText(_translate("MainWindow", "Log"))
        self.pushButton_6.setText(_translate("MainWindow", "SQRT"))
        self.pushButton_7.setText(_translate("MainWindow", "Colour"))
        # Pressure-guess tab widget headers are set per-tab dynamically
        # in EXODUS_main._rebuild_pressure_guess_tabs(); nothing to set here.
        self.label_7.setText(_translate("MainWindow", "2D Plot and fits"))
